### ISSUE TITLE
More lighboxes are opened when the "Enter" key is pressed on an expanded image.

### ISSUE THREAD

**Issue by ryandonsullivan** [noelboss/featherlight#151] opened 2015-07-17 04:54 UTC
When an image is expanded within a lighbox, if you press the enter key on the keyboard, it opens an identical lightbox on top of the existing one. This can be replicated infinite number of times as far as we can tell, and every subsequent lightbox has to be closed one by one in order for the lightbox to be closed.

Here's a quick demo of the bug: http://g.recordit.co/w47jYHOy3c.gif

When the screen flashes the first 6 times, I'm hitting the enter key. Then you can see the screen flash six more times when I click the close button.

This is using the default markup with no customizations.

I hope that's not too confusing. If you need additional details I'll be happy to provide them. Thanks in advance.

**Comment by marcandre** [comment] 2015-07-17 10:06
Interesting. I think what’s happening is that the image still has the focus, so pressing `enter` is like clicking on it, even though you can’t click on it with the mouse because of the opened dialog.
If you want to avoid this for now, I’m guessing that removing the focus in `afterOpen` will fix this.

**Comment by ryandonsullivan** [comment] 2015-07-20 15:08
Thanks for following up so quickly. Really appreciate it @marcandre!

**Comment by robneu** [comment] 2015-08-17 08:40
It does look like this is the cause of the issue. Doing the following seems to solve the problem:

```javascript
$.featherlight.prototype.afterOpen = function() {
	this.$currentTarget.blur();
};
```

**Comment by marcandre** [comment] 2015-08-18 02:38
Fixed in `master`. Thanks for reporting this :smile:

**Closed by marcandre** 2015-08-18 02:38 UTC
Labels: bug
