### ISSUE TITLE
Make close icon hyperlink (a tag) instead of span

### ISSUE THREAD

**Issue by prasad83** [noelboss/featherlight#169] opened 2015-08-28 09:14 UTC
With (close-icon) being span had difficulty get the click working in mobile devices. 
Changed it to <a href="#"...

**Comment by marcandre** [comment] 2015-08-28 17:23
I'm not sure I understand how an `<a href="#">` or a `<span>` will behave differently when clicked... Both should have the same area and respond the same way

**Comment by janjaap** [comment] 2015-11-02 11:50
Semantically, it shouldn't be an `<a>` tag, because it's 'href' attribute has no meaningful value. Might be better to make it a `<button>` element if `<span>` causes `onclick` problems.

**Comment by marcandre** [comment] 2015-11-03 08:46
Right, but `<button>` has user-agent styling that we don't want.
Closing this as no reproducible issue with current code.

**Closed by marcandre** 2015-11-03 08:46 UTC
